name: Validate Mono versions
on:
  workflow_dispatch:

jobs:
  mono-125-mono:
    name: Mono 6.12.0.125 Nuget restore
    runs-on: macos-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-125-dotnet:
    name: Mono 6.12.0.125 dotnet restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - name: dotnet restore
      run: dotnet restore ./Todo/Todo.sln

  mono-125-msbuild:
    name: Mono 6.12.0.125 msbuild restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Mono version
      run: mono --version
    - name: msbuild restore
      run: msbuild -t:restore ./Todo/Todo.sln

  mono-140-nuget:
    name: Mono 6.12.0.140 Nuget restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-140-dotnet:
    name: Mono 6.12.0.140 dotnet restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - name: dotnet restore
      run: dotnet restore ./Todo/Todo.sln

  mono-140-msbuild:
    name: Mono 6.12.0.140 msbuild restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-140.sh
    - name: Mono version
      run: mono --version
    - name: msbuild restore
      run: msbuild -t:restore ./Todo/Todo.sln

  mono-147-nuget:
    name: Mono 6.12.0.147 Nuget restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - name: Nuget restore
      run: nuget restore ./Todo/Todo.sln

  mono-147-dotnet:
    name: Mono 6.12.0.147 dotnet restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - name: dotnet restore
      run: dotnet restore ./Todo/Todo.sln

  mono-147-msbuild:
    name: Mono 6.12.0.147 msbuild restore
    runs-on: macos-10.15
    steps:    
    - uses: actions/checkout@v2
    - name: Remove current Mono
      run: sudo rm -rf /Library/Frameworks/Mono.framework/Versions/6.12.0
    - name: Install new Mono
      run: bash ./install-mono-147.sh
    - name: Mono version
      run: mono --version
    - name: msbuild restore
      run: msbuild -t:restore ./Todo/Todo.sln
